<?php
$table_1_config = $this->config->table_1->toArray();
echo '<p>PHP: <b>'.phpversion().'</b> Phalcon: <b>'.Phalcon\Version::get().'</b></p>';
?>

<p>
Built with <a href="https://phalconphp.com">Phalcon</a> PHP framework and <a href="https://www.datatables.net/">DataTables</a> plug-in for jQuery. 
</p>

<div class="page-header">
    <h1>Congratulations!</h1>
</div>


<table id="table_1" class="table table-striped table-bordered" cellspacing="0" width="100%">
	<thead>
		<tr>
		<?php
		
		foreach ($table_1_config['columns'] as $c) echo '<th style="text-align: '.$c['align'].';">'.$c['label'].'</th>';
		?>
		</tr>
	</thead>
	<tbody>
	</tbody>
</table>

<script type="text/javascript">
	$(document).ready( function () {
    	$('#table_1').DataTable( {
            "processing": true,
            "serverSide": true,
            "pagingType": "full_numbers",
            "sServerMethod": "POST",
            "ajax": "/data/table1",
            "aLengthMenu": [[10, 20, 50], [10, 20, 50]],
            "columnDefs": [
				{ className: "text-center", "targets": <?=$table_1_config['align_center']?> },
				{ className: "text-right", "targets": <?=$table_1_config['align_right']?> },
			]
        } );
	});
</script>
