<?php
echo '<p>PHP: <b>'.phpversion().'</b> Phalcon: <b>'.Phalcon\Version::get().'</b></p>';
?>

<div class="page-header">
    <h1>Congratulations!</h1>
</div>


<table id="table_1" class="table table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>Column 1</th>
            <th>Column 2</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Row 1 Data 1</td>
            <td>Row 1 Data 2</td>
        </tr>
        <tr>
            <td>Row 2 Data 1</td>
            <td>Row 2 Data 2</td>
        </tr>
    </tbody>
</table>

<script type="text/javascript">
	$(document).ready( function () {
    	$('#table_1').DataTable();
	});
</script>
